version: '3'
services:
  geth:
    container_name: node
    build:
      context: ./
    ports:
      - 8545:8545
      - 8546:8546
      - 30301:30301
    volumes:
      - ./genesis.json:/app/genesis.json
      - ./static-nodes.json:/app/static-nodes.json
      - /data